### ISSUE TITLE
ID asking for payer benefits credit: 
User feedback: language
(`asking_for_payer_benefits_credit`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHMotionRegardingChildSupport#73]
Question ID | `asking for payer benefits credit`
Details | There are two questions on the same page about the dependent benefit credit that are asking the same thing; I think we should just have the question at the top and delete the second one. 

In the agreement, are you asking the court to give the payer of child support a credit each month for dependent benefits received from a government insurance program?
If the payer of child support receives retirement, survivor’s, or disability benefits from a government insurance program such as Social Security, Veteran’s Administration, or Railroad Retirement, the payer’s dependent children may also get benefits based on the payer’s work record. The court will credit these dependent benefits towards payment of child support. In other words, the amount of dependent benefits should be subtracted from the support amount.

Are you asking for the court to give you a credit?

**Comment by ekressmiller** [comment]
Question for Amy:

If we delete the second label, I'd suggest changing the "yes" and "no" answers to be more descriptive since they'll be pretty separated from the question. For example:
![image](https://github.com/user-attachments/assets/a2fc65be-046e-44a4-b8f5-21572abc246c)

In creating those, it made me wonder: if the children **are** getting dependent benefits, does the parent really have any choice about whether the court gives a credit or not? If not, would it be better to just ask whether they're getting the benefits instead of whether the parent wants to ask for a credit?

**Comment by ABillmire** [comment]
You're right, the parent doesn't have a choice. "Asking" here was just a stand in for letting the court know there is a dependent benefit. I agree with your suggestion.

**Comment by ekressmiller** [comment]
@ABillmire how's this?

![image](https://github.com/user-attachments/assets/4a15cd73-7b3b-4f0f-a761-11a2a74bd39f)

![image](https://github.com/user-attachments/assets/b3190012-03c0-479e-ad57-d76e6de4b194)

**Comment by ABillmire** [comment]
@ekressmiller Those are great! Thank you!
